### ISSUE TITLE
Heated bed does not allow you to set to BED_MAXTEMP

### ISSUE THREAD

**Issue by mike-8502** [LittleHobbyShop/SunluS8#2]
The following line in Configuration.h is set to 
#define BED_MAXTEMP      95

However when going to Temperature>Bed on the LCD menu you can only set to 85

**Comment by mike-8502** [comment]
Found this in temperature.h

static void setTargetBed(const int16_t celsius) {
        #if ENABLED(AUTO_POWER_CONTROL)
          powerManager.power_on();
        #endif
        temp_bed.target =
          #ifdef BED_MAXTEMP
            _MIN(celsius, BED_MAXTEMP - 10)
          #else
            celsius
          #endif
        ;
        start_watching_bed();
      }


Probably related to:
[BUG] Marlin 2.0.5.3 only heats up to HEATER_0_MAXTEMP minus 15 Degrees #17693

**Comment by mike-8502** [comment]
Confirmed its a Marlin 2.0.5.3 issue/feature

HEATER_0_MAXTEMP 275  //will be; 275-15 or 260

and

BED_MAXTEMP      //95 will be; 95-10 or 85

Fix for now would be to set the value higher, by these offsets. There at least needs be e a comment in the Configuration.h of the Marlin 2.0.5.3 release.

**Comment by LittleHobbyShop** [comment]
This safety offset was introduced in Marlin 1.1.9. The official releases from Sunlu are also of that version and include a BED_MAXTEMP of 95. Therefore I can only assume it is known and intentional and in fact the bed is only intended to reach 80 (the original limit in 1.1.9 was max - 15). Without knowing more about the hardware I'm reluctant to raise it here, particularly with the plastic cable relief mounted to the back of the bed.

**Comment by mike-8502** [comment]
Close this issue.

From reading Marlin's bug tracker it has tripped up a few people. As stated in my previous comments, the marlin group should note the the temp offsets in the Config.h file to avoid confusion.

I'll go there to get insulted ;>)

**Comment by LittleHobbyShop** [comment]
@mike-8502 please be careful of that strain relief at the back. It looks like it might be ABS which has a glass transition temp of 105 so you would think it would be OK but might go a bit soft especially with the bed moving around rather than a static test. Thanks for the feedback and happy (safe) printing :)
